image: node:16

stages:
  - build
  - test
  - deploy

install:
  stage: build
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
  needs:
    - job: install
      artifacts: true

lint:
  stage: test
  script:
    - npm run lint
  needs:
    - job: install
      artifacts: true

unit:
  stage: test
  script:
    - npm run test:unit -- run
  needs:
    - job: install
      artifacts: true

deploy:
  stage: deploy
  script:
    - npm run deploy -- --token $SURGE_TOKEN
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  needs:
    - job: install
      artifacts: true
    - job: build
      artifacts: true