name: VueJS CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: prepare
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: prepare
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: unit test
        run: npm run test:unit -- run
      - name: build
        run: npm run build
      - name: e2e
        uses: cypress-io/github-action@v4.2.0
        with:
          command: npm run test:e2e
      - name: deploy
        if: steps.prepare.outputs.branch == 'main'
        run: npm run deploy -- --token ${{ secrets.SURGE_TOKEN }}